### ISSUE TITLE
Add "overflow-y: auto" to catergory bar style

### ISSUE THREAD

**Issue by sungik-choi** [sungik-choi/gatsby-starter-apple#20]
Currently, the attribute `overflow-y: scroll` is applied, so unnecessary scroll bars are exposed every time.

**Comment by marksteven** [comment]
Tried this and it worked OK
const CategoryUl = styled.ul`
  display: flex;  
  flex-wrap: wrap;
  list-style: none;
  overflow-x: scroll;
  -ms-overflow-style: none;
  scrollbar-width: none;

  li + li {
    margin-left: 6px;
  }
`

**Comment by dwootton** [comment]
The previous answer didn't work for me, but this did: 
`const CategoryUl = styled.ul`
  display: flex;
  list-style: none;
  overflow-x: scroll;
  -ms-overflow-style: none;
  scrollbar-width: none;

  li + li {
    margin-left: 6px;
  }

  &::-webkit-scrollbar {
    background: transparent; /* Chrome/Safari/Webkit */
    width: 0px;
    height:0px;
  }
``
