### ISSUE TITLE
Build time, deprecated packages

### ISSUE THREAD

**Issue by donnydark0** [sungik-choi/gatsby-starter-apple#37]
Hi,
the build time is very long on Vercel. More often than not changes are not visible on the website, because the new build failed. Even after redeploying the changes are still not there, which is especially odd, since the old files don't exist anymore in my repo.
I tried to run it locally and npm install took forever as well. It loaded hundreds of deprecated packages.

**Comment by sungik-choi** [comment]
Fixed by #45
