### ISSUE TITLE
Create Gatsby Site from starter 

### ISSUE THREAD

**Issue by thedomcab** [sungik-choi/gatsby-starter-apple#49]
I am having many errors for creating a gatsby site from blog starter.  There are many errors and I cannot find out what is the cause. 
[eresolve-report.txt](https://github.com/sungik-choi/gatsby-starter-apple/files/10117393/eresolve-report.txt)
 
could someone help me resolve this issues?

**Comment by evewolfs** [comment]
Same here, it throws error. By doing npm install, it stops showing error but then "gatsby develop" just runs endlessly. Such a wonderful template, I hope we can solve it!
[eresolve-report.txt](https://github.com/sungik-choi/gatsby-starter-apple/files/10181035/eresolve-report.txt)

**Comment by dwootton** [comment]
Had the same issue. Did an `npm update` and it resolved the issue. @evewolfs, mine is also running endlessly but my site is still served at http://localhost:8000/. Is yours not?

**Comment by pumpknman** [comment]
@dwootton
I have the same issue, but my site is still served at localhost. However I still get this endless messages and the changes I make to the file is not applied in realtime. @sungik-choi any advise?

**Comment by sungik-choi** [comment]
I don't have the time to maintain the library at the moment, so I'll be looking into the issue in May. If anyone can fix it, contributions are welcome.

**Comment by sungik-choi** [comment]
@thedomcab @evewolfs @dwootton @pumpknman 

I changed the package manager from npm to yarn. This seems to have fixed the problem, so I'd appreciate it if you could apply the new version.
