### ISSUE TITLE
Error directly after cloning and running gatsby develop

### ISSUE THREAD

**Issue by jaypatrick** [sungik-choi/gatsby-starter-apple#56]
I've tried cloning numerous times, always get the following error upon attempting gatsby develop

success compile gatsby files - 0.714s

 ERROR  UNKNOWN

There was a problem loading plugin "gatsby-source-filesystem". Perhaps you need to install its package?
Use --verbose to see actual error.

 ERROR  UNKNOWN

Failed to resolve gatsby-source-filesystem unreachable

  Error: unreachable

  - resolve-plugin.ts:95 resolvePlugin
    [jayson.knight]/[gatsby]/src/bootstrap/load-plugins/resolve-plugin.ts:95:11

  - index.ts:54 resolveTheme
    [jayson.knight]/[gatsby]/src/bootstrap/load-themes/index.ts:54:42

  - index.ts:164
    [jayson.knight]/[gatsby]/src/bootstrap/load-themes/index.ts:164:30

  - util.js:16 tryCatcher
    [jayson.knight]/[bluebird]/js/release/util.js:16:23

  - reduce.js:166 Object.gotValue
    [jayson.knight]/[bluebird]/js/release/reduce.js:166:18

  - reduce.js:155 Object.gotAccum
    [jayson.knight]/[bluebird]/js/release/reduce.js:155:25

  - util.js:16 Object.tryCatcher
    [jayson.knight]/[bluebird]/js/release/util.js:16:23

  - promise.js:547 Promise._settlePromiseFromHandler
    [jayson.knight]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [jayson.knight]/[bluebird]/js/release/promise.js:604:18

  - promise.js:641 Promise._settlePromiseCtx
    [jayson.knight]/[bluebird]/js/release/promise.js:641:10

  - async.js:97 _drainQueueStep
    [jayson.knight]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [jayson.knight]/[bluebird]/js/release/async.js:86:9

  - async.js:102 Async._drainQueues
    [jayson.knight]/[bluebird]/js/release/async.js:102:5

  - async.js:15 Immediate.Async.drainQueues [as _onImmediate]
    [jayson.knight]/[bluebird]/js/release/async.js:15:14

  - timers:475 processImmediate
    node:internal/timers:475:21

not finished load gatsby config - 0.102s

**Comment by sungik-choi** [comment]
@jaypatrick 

I changed the package manager from npm to yarn. This seems to have fixed the problem, so I'd appreciate it if you could apply the new version.
